---
version: "3"

services:
  
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - backend
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: stu
      
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 5s
      retries: 40
  
  backend:
    build: ./
    restart: always
    depends_on:
      db:
        condition: service_healthy

    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:
    driver: bridge
